/**
 * @fileoverview Curated India FEO + NIA most-wanted records used by the
 * `india_watchlist` ingester. These names are not on the UAPA terrorist
 * schedules (that corpus is `india_uapa`). UN and UAPA rows from the source
 * compilation are omitted so they are not duplicated.
 * @module services/screening/india-watchlist-data
 */

export interface IndiaWatchlistRecord {
  aliases: string[];
  category: 'FUGITIVE_ECONOMIC_OFFENDER' | 'NIA_MOST_WANTED';
  dob: string | null;
  id: string;
  name: string;
  nationality: string | null;
  place_of_birth: string | null;
  source: string;
  source_url: string;
}

/**
 * Fugitive Economic Offenders + NIA Most Wanted compiled from public
 * Government of India / parliamentary reporting. Not a live ED/NIA bulk feed.
 */
export const INDIA_WATCHLIST_RECORDS: readonly IndiaWatchlistRecord[] = [
  {
    id: 'FEO-001',
    name: 'Nirav Modi',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'FEO-002',
    name: 'Vijay Mallya',
    aliases: [],
    dob: '1955-12-18',
    place_of_birth: 'Delhi, India',
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'FEO-003',
    name: 'Nitin J. Sandesara',
    aliases: ['Nitin Sandesara', 'Nitin J Sandesara'],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'FEO-004',
    name: 'Chetan J. Sandesara',
    aliases: ['Chetan Sandesara', 'Chetan J Sandesara'],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'FEO-005',
    name: 'Dipti C. Sandesara',
    aliases: ['Dipti Sandesara', 'Dipti C Sandesara'],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'FEO-006',
    name: 'Sudharshan Venkatraman',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'FEO-007',
    name: 'Ramanujam Sesharathnam',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'FEO-008',
    name: 'Pushpesh Kumar Baid',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'FEO-009',
    name: 'Hitesh Kumar Narendrabhai Patel',
    aliases: ['Hitesh Patel'],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'FUGITIVE_ECONOMIC_OFFENDER',
    source: 'Enforcement Directorate (Govt.)',
    source_url:
      'https://www.livemint.com/news/india/vijay-mallya-nirav-modi-among-15-declared-fugitive-economic-offenders-owe-58-000-crore-to-psbs-govt-in-parliament-11764634470794.html',
  },
  {
    id: 'NIA-001',
    name: 'Ramchandra Kalsangra',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-002',
    name: 'Sandeep Dange',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-003',
    name: 'Junaid Ahmed',
    aliases: ['Junaid Ahmed A-2', 'Junaid Ahmed A2'],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-004',
    name: 'Abubakkar Siddik',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-005',
    name: 'Masud K A',
    aliases: ['Masud K A A-5'],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-006',
    name: 'Ummar R',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-007',
    name: 'Furkhan Bhai',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-008',
    name: 'Siddique bin Osman',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-009',
    name: 'Zakir',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-010',
    name: 'Aman Purewal',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-011',
    name: 'Ankit Shokeen',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-012',
    name: 'Bachittar Singh',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-013',
    name: 'Gurjant Singh',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-014',
    name: 'Baljot Singh',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-015',
    name: 'Harjit Singh',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
  {
    id: 'NIA-016',
    name: 'Harwinder Kumar',
    aliases: [],
    dob: null,
    place_of_birth: null,
    nationality: 'India',
    category: 'NIA_MOST_WANTED',
    source: 'National Investigation Agency (India)',
    source_url: 'https://nia.gov.in/most-wanted-photos',
  },
];
