/**
 * @fileoverview UAE Local Terrorist List (EOCN) — bundled static records.
 *
 * The official source is the UAE Executive Office for Control and
 * Non-Proliferation (EOCN) at eocn.gov.ae, which publishes the list under
 * Cabinet Decision No. 83 of 2021 and subsequent amendments. The site is
 * protected by a WAF that prevents automated fetching, so this list is
 * maintained as a curated static dataset.
 *
 * HOW TO UPDATE
 * 1. Obtain the current Excel/PDF from the official EOCN portal.
 * 2. Run: bun run scripts/import-uae-local.ts <path-to-new-pdf>
 * 3. Commit the regenerated file.
 * 4. Re-run `bun run mirror:refresh` to ingest.
 *
 * Generated from: /Users/mobcoderid-245/Downloads/Copy of SL_1 (24052021) V.2.pdf
 * Persons: 106 | Entities: 113 | Total: 219
 * @module services/screening/uae-local-data
 */

/** Snapshot date of the last manual update to this file (ISO 8601). */
export const UAE_LOCAL_VERSION = '2026-09-21';

/** Provenance URL — the official EOCN page operators should check for updates. */
export const UAE_LOCAL_SOURCE_URL = 'https://www.eocn.gov.ae/en/CrimesPrevention/LocalTerroristList';

export type UaeEntityType = 'person' | 'organization';

export interface UaeLocalRecord {
  id: string;
  name: string;
  aliases: string[];
  type: UaeEntityType;
  dob?: string;
  nationality?: string;
  passportNumber?: string;
  legalBasis?: string;
}

export const UAE_LOCAL_RECORDS: readonly UaeLocalRecord[] = [
  {
    id: 'UAE-P-001',
    name: 'KHALIFA MOHD T AL SUBAEY',
    aliases: ['AL SUBAEY'],
    type: 'person',
    dob: '1965-01-01',
    passportNumber: '685868',
  },
  {
    id: 'UAE-P-002',
    name: 'ABDULMALIK MOHAMMAD YOUSEF ABDELSALAM',
    aliases: ['ABDELSALAM'],
    type: 'person',
    dob: '1989-07-13',
    passportNumber: '475336',
  },
  {
    id: 'UAE-P-003',
    name: 'ASHRAF MUHAMMAD YUSUF UTHMAN ABD ALSALAM',
    aliases: ['ABD AL SALAM'],
    type: 'person',
  },
  {
    id: 'UAE-P-004',
    name: 'IBRAHIM \'ISA HAJJI MUHAMMAD AL-BAKR',
    aliases: ['AL-BAKR'],
    type: 'person',
    dob: '1977-07-12',
    passportNumber: '01016646',
  },
  {
    id: 'UAE-P-005',
    name: 'ABDULAZIZ BIN KHALIFA ALATTIYAH',
    aliases: ['ALATTIYAH'],
    type: 'person',
  },
  {
    id: 'UAE-P-006',
    name: 'SALIM HASAN KHALIFA RASHID AL-KUWARI',
    aliases: ['AL-KUWARI'],
    type: 'person',
  },
  {
    id: 'UAE-P-007',
    name: 'ABDALLAH GHANIM MAHFUZ MUSLIM AL-KHAWAR',
    aliases: ['AL-KHAWAR'],
    type: 'person',
    dob: '1981-12-17',
  },
  {
    id: 'UAE-P-008',
    name: 'SA\'D BIN SA\'D MUHAMMAD SHARIAN AL-KA\'BI',
    aliases: ['AL-KA\'BI'],
    type: 'person',
  },
  {
    id: 'UAE-P-009',
    name: 'ABD AL-LATIF BIN ABDALLAH SALIH MUHAMMAD AL-KAWARI',
    aliases: ['AL-KUWARI'],
    type: 'person',
    dob: '1973-09-28',
  },
  {
    id: 'UAE-P-010',
    name: 'MOHAMMAD SAEED BIN HELWAN AL-SEQATRI',
    aliases: ['AL-SEQATRI'],
    type: 'person',
  },
  {
    id: 'UAE-P-011',
    name: 'ABD AL-RAHMAN BIN \'UMAYR AL-NU\'AYMI',
    aliases: ['AL-NU\'AYMI'],
    type: 'person',
    dob: '1951-05-06',
  },
  {
    id: 'UAE-P-012',
    name: 'ABD AL-WAHHAB MUHAMMAD ABD AL-RAHMAN AL-HUMAYQANI',
    aliases: ['AL-HUMAYQANI'],
    type: 'person',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-013',
    name: 'KHALIFA BIN MOHAMMAD AL-RABBAN',
    aliases: ['AL-RABBAN'],
    type: 'person',
  },
  {
    id: 'UAE-P-014',
    name: 'ABDULLAH BIN KHALID BIN HAMAD BIN ABDULLAH AL-THANI',
    aliases: ['AL-THANI'],
    type: 'person',
  },
  {
    id: 'UAE-P-015',
    name: 'ABDUL RAHIM AHMAD AL-HARAM',
    aliases: ['AL-HARAM'],
    type: 'person',
  },
  {
    id: 'UAE-P-016',
    name: 'HAJJAJ BIN FAHD HAJJAJ MUHAMMAD AL-AJMI',
    aliases: ['AL-AJMI'],
    type: 'person',
    dob: '1987-08-10',
    passportNumber: '107706887',
  },
  {
    id: 'UAE-P-017',
    name: 'MUBARAK MOHAMMAD AL-AJJI',
    aliases: ['AL-AJJI'],
    type: 'person',
  },
  {
    id: 'UAE-P-018',
    name: 'JABIR BIN NASSER AL-MARRI',
    aliases: ['AL-MARRI'],
    type: 'person',
  },
  {
    id: 'UAE-P-019',
    name: 'YUSUF ABDULLAH AL-QARADAWI',
    aliases: ['AL-QARADAWI'],
    type: 'person',
    dob: '1963-01-13',
    passportNumber: '5113',
  },
  {
    id: 'UAE-P-020',
    name: 'MOHAMMED JASSIM AL-SULAITI',
    aliases: ['AL-SULAITI'],
    type: 'person',
  },
  {
    id: 'UAE-P-021',
    name: 'ALI BIN ABDALLAH AL-SUWAIDI',
    aliases: ['AL-SUWAIDI'],
    type: 'person',
  },
  {
    id: 'UAE-P-022',
    name: 'HASHIM SALEH ABDULLAH AL-AWADHY',
    aliases: ['AL-AWADHY'],
    type: 'person',
  },
  {
    id: 'UAE-P-023',
    name: 'ALI MOHAMMED MOHAMMED AL-SALLABI',
    aliases: ['AL-SALLABI'],
    type: 'person',
    dob: '1976-01-01',
  },
  {
    id: 'UAE-P-024',
    name: 'ABD AL-HAKIM BELHAJ',
    aliases: ['BELHAJ'],
    type: 'person',
    dob: '1966-05-01',
    passportNumber: 'ياȎلي',
  },
  {
    id: 'UAE-P-025',
    name: 'MAHDI AL-HARATI',
    aliases: ['AL-HARATI'],
    type: 'person',
  },
  {
    id: 'UAE-P-026',
    name: 'ISMAIL MOHAMMED MOHAMMED AL-SALLABI',
    aliases: ['AL-SALLABI'],
    type: 'person',
  },
  {
    id: 'UAE-P-027',
    name: 'AL-SADIQ ABD-ALRAHMAN ALI AL-QHRIANY',
    aliases: ['AL-QHRIANY'],
    type: 'person',
    dob: '1942-12-08',
  },
  {
    id: 'UAE-P-028',
    name: 'HAMAD ABDULLAH AL-FUTTAIS AL-MARRI',
    aliases: ['AL-MARRI'],
    type: 'person',
  },
  {
    id: 'UAE-P-029',
    name: 'MOHAMMED AHMED SHAWQI ISLAMBOULI',
    aliases: ['ISLAMBOULI'],
    type: 'person',
    dob: '1952-01-21',
    passportNumber: '304555',
  },
  {
    id: 'UAE-P-030',
    name: 'TAREK ABD AL-MAWGOUD IBRAHIM AL-ZUMAR',
    aliases: ['AL-ZUMAR'],
    type: 'person',
    dob: '1959-05-15',
  },
  {
    id: 'UAE-P-031',
    name: 'MOHAMMED ABD AL-MAQSOUD MOHAMMED AFIFI',
    aliases: ['AFIFI'],
    type: 'person',
    dob: '1947-07-14',
  },
  {
    id: 'UAE-P-032',
    name: 'MOHAMMAD ELSAGHEER ABD AL-RAHIM MOHAMMED',
    aliases: ['MOHAMMED'],
    type: 'person',
    dob: '1970-04-13',
    passportNumber: 'A08670835',
  },
  {
    id: 'UAE-P-033',
    name: 'WAGDY ABDEL HAMIED MOHAMED GHONIEM',
    aliases: ['GHONIEM'],
    type: 'person',
    dob: '1951-08-02',
    passportNumber: '4155047',
  },
  {
    id: 'UAE-P-034',
    name: 'HASSAN AHMED HASSAN MOHAMED AL-DIQQI AL-HOUTI',
    aliases: ['AL-HOUTI'],
    type: 'person',
    dob: '1957-01-03',
    passportNumber: '2116728',
  },
  {
    id: 'UAE-P-035',
    name: 'HAKEM OBAYSAN AL-HAMIDI AL-MUTAIRI',
    aliases: ['AL-MUTAIRI'],
    type: 'person',
    dob: '1964-11-07',
    passportNumber: '3229745',
  },
  {
    id: 'UAE-P-036',
    name: 'ABDALLAH MUHAMMAD BIN SULAYMAN AL-MUHAYSINI',
    aliases: ['AL-MUHAYSINI'],
    type: 'person',
    dob: '1987-10-30',
  },
  {
    id: 'UAE-P-037',
    name: 'HAMID ABDALLAH AHMAD AL-ALI',
    aliases: ['AL-ALI'],
    type: 'person',
    dob: '1960-01-20',
  },
  {
    id: 'UAE-P-038',
    name: 'AYMAN AHMED ABDUL GHANI HASSANEIN',
    aliases: ['HASSANEIN'],
    type: 'person',
    dob: '1964-11-01',
  },
  {
    id: 'UAE-P-039',
    name: 'ASSEM ABDEL-MAGED MOHAMMED MADI',
    aliases: ['MADI'],
    type: 'person',
  },
  {
    id: 'UAE-P-040',
    name: 'YAHYA AQIL SALMAN AQEEL',
    aliases: ['AQEEL'],
    type: 'person',
  },
  {
    id: 'UAE-P-041',
    name: 'MOHAMED HAMADA EL-SAYED IBRAHIM',
    aliases: ['IBRAHIM'],
    type: 'person',
    dob: '1982-01-20',
    passportNumber: '11180132',
  },
  {
    id: 'UAE-P-042',
    name: 'ABDEL RAHMAN MOHAMED SHOKRY ABDEL RAHMAN',
    aliases: ['ABDEL RAHMAN'],
    type: 'person',
  },
  {
    id: 'UAE-P-043',
    name: 'HUSSEIN MOHAMED REZA IBRAHIM YOUSSEF',
    aliases: ['YOUSSEF'],
    type: 'person',
  },
  {
    id: 'UAE-P-044',
    name: 'AHMED ABDELHAFID MAHMOUD ABDELHADY',
    aliases: ['ABDELHADY'],
    type: 'person',
  },
  {
    id: 'UAE-P-045',
    name: 'MUSLIM FOUAD TARFAN',
    aliases: ['TARFAN'],
    type: 'person',
  },
  {
    id: 'UAE-P-046',
    name: 'AYMAN MAHMOUD SADEQ RIFAT',
    aliases: ['RIFAT'],
    type: 'person',
  },
  {
    id: 'UAE-P-047',
    name: 'MOHAMED SAAD ABDEL-NAIM AHMED',
    aliases: ['AHMED'],
    type: 'person',
  },
  {
    id: 'UAE-P-048',
    name: 'MOHAMED SAAD ABDEL MUTTALIB ABDO AL-RAZAFI',
    aliases: ['AL-RAZAKI'],
    type: 'person',
  },
  {
    id: 'UAE-P-049',
    name: 'AHMED FOUAD AHMED GAD BELTAGY',
    aliases: ['BELTAGY'],
    type: 'person',
    dob: '1980-01-01',
    passportNumber: '1147218',
  },
  {
    id: 'UAE-P-050',
    name: 'AHMED RAGEB RAGEB SOLIMAN',
    aliases: ['SOLIMAN'],
    type: 'person',
  },
  {
    id: 'UAE-P-051',
    name: 'KARIM MOHAMED MOHAMED ABDEL AZIZ',
    aliases: ['ABDEL AZIZ'],
    type: 'person',
  },
  {
    id: 'UAE-P-052',
    name: 'ALI ZAKI MOHAMMED ALI',
    aliases: ['ALI'],
    type: 'person',
  },
  {
    id: 'UAE-P-053',
    name: 'NAJI IBRAHIM EZZOULI',
    aliases: ['EZZOULI'],
    type: 'person',
  },
  {
    id: 'UAE-P-054',
    name: 'SHEHATA FATHI HAFEZ MOHAMMED SULEIMAN',
    aliases: ['SULEIMAN'],
    type: 'person',
  },
  {
    id: 'UAE-P-055',
    name: 'MUHAMMAD MUHARRAM FAHMI ABU ZEID',
    aliases: ['ABU ZEID'],
    type: 'person',
  },
  {
    id: 'UAE-P-056',
    name: 'AMR ABDEL NASSER ABDELHAK ABDEL-BARRY',
    aliases: ['ABDEL-BARRY'],
    type: 'person',
  },
  {
    id: 'UAE-P-057',
    name: 'ALI HASSAN IBRAHIM ABDEL-ZAHER',
    aliases: ['ABDEL-ZAHER'],
    type: 'person',
  },
  {
    id: 'UAE-P-058',
    name: 'MURTADHA MAJEED AL-SINDI',
    aliases: ['AL-SINDI'],
    type: 'person',
  },
  {
    id: 'UAE-P-059',
    name: 'AHMED AL-HASSAN AL-DASKI',
    aliases: ['AL-DASKI'],
    type: 'person',
  },
  {
    id: 'UAE-P-060',
    name: 'ABDULLAH MOHAMMED AL-YAZIDI',
    aliases: ['AL-YAZIDI'],
    type: 'person',
    dob: '1957-01-01',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-061',
    name: 'AHMED ALI AHMED BAROAUD',
    aliases: ['BAROAUD'],
    type: 'person',
    dob: '1965-01-01',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-062',
    name: 'MOHAMMED BAKR AL-DABAA',
    aliases: ['AL-DABAA'],
    type: 'person',
    dob: '1958-01-08',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-063',
    name: 'KHALID SAEED AL-BOUNEIN',
    aliases: ['AL-BOUNEIN'],
    type: 'person',
    dob: '1968-01-01',
  },
  {
    id: 'UAE-P-064',
    name: 'SHAQER JUMMAH AL-SHAHWANI',
    aliases: ['AL-SHAHWANI'],
    type: 'person',
  },
  {
    id: 'UAE-P-065',
    name: 'SALEH BIN AHMED AL-GHANIM AL-KUWARI',
    aliases: ['AL-KUWARI'],
    type: 'person',
  },
  {
    id: 'UAE-P-066',
    name: 'HAMID HAMAD HAMID AL-\'ALI',
    aliases: ['AL-\'ALI'],
    type: 'person',
    dob: '1960-02-17',
    passportNumber: '101505554',
  },
  {
    id: 'UAE-P-067',
    name: 'AL-SAADI ABDULLAH IBRAHIM BUKHAZEM',
    aliases: ['BUKHAZEM'],
    type: 'person',
    dob: '1981-11-21',
  },
  {
    id: 'UAE-P-068',
    name: 'AHMED ABD AL-JALEEL AL-HASNAWI',
    aliases: ['AL-HASNAWI'],
    type: 'person',
    passportNumber: '54390612',
  },
  {
    id: 'UAE-P-069',
    name: 'NAYIF SALIH SALIM AL-QAYSI',
    aliases: ['AL-QAYSI'],
    type: 'person',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-070',
    name: 'HASHIM MUHSIN AYDARUS',
    aliases: ['AYDARUS'],
    type: 'person',
    dob: '1985-12-12',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-071',
    name: 'NASHWAN AL-ADANI',
    aliases: ['AL-ADANI'],
    type: 'person',
    dob: '1988-01-13',
    nationality: 'Yemen',
    passportNumber: '2017ࢫلسنة (45)ࢫرمࢫالوزراءࢫمجلسࢫارࢫبموجبࢫمدرج',
  },
  {
    id: 'UAE-P-072',
    name: 'KHALID ABDULLAH AL-MARFADI',
    aliases: ['AL-MARFADI'],
    type: 'person',
    dob: '1966-09-04',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-073',
    name: 'SAIFULRAB SALIM AL-HEESHI',
    aliases: ['AL-HEESHI'],
    type: 'person',
    dob: '1978-01-01',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-074',
    name: 'ADEL ABDU FARI OTHMAN AL-THAHBANI',
    aliases: ['AL-THAHBANI'],
    type: 'person',
    dob: '1963-07-15',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-075',
    name: 'RADWAN QANAN',
    aliases: ['QANAN'],
    type: 'person',
    dob: '1988-01-13',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-076',
    name: 'WALI NASHWAN AL-YAFI\'I',
    aliases: ['AL-YAFI\'I'],
    type: 'person',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-077',
    name: 'KHALID SA\'ID GHABISH AL-UBAYDI',
    aliases: ['AL-UBAYDI'],
    type: 'person',
    dob: '1986-11-18',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-078',
    name: 'BILAL ALI AL-WAFI',
    aliases: ['AL-WAFI'],
    type: 'person',
    nationality: 'Yemen',
  },
  {
    id: 'UAE-P-079',
    name: 'KHALID NAZEM DIAB',
    aliases: ['DIAB'],
    type: 'person',
  },
  {
    id: 'UAE-P-080',
    name: 'SALEM JABER OMAR ALI SULTAN FATHALLAH JABER',
    aliases: ['JABER'],
    type: 'person',
  },
  {
    id: 'UAE-P-081',
    name: 'MAYSAR ALI MUSA ABDALLAH AL-JUBURI',
    aliases: ['AL-JUBURI'],
    type: 'person',
    dob: '1976-06-01',
  },
  {
    id: 'UAE-P-082',
    name: 'MOHAMMED ALI SAEED ATM',
    aliases: ['ATM'],
    type: 'person',
  },
  {
    id: 'UAE-P-083',
    name: 'HASAN ALI MOHAMMED JUMA\'A SULTAN',
    aliases: ['SULTAN'],
    type: 'person',
  },
  {
    id: 'UAE-P-084',
    name: 'MOHAMMED SULAIMAN HAIDAR MOHAMMED AL-HAYDAR',
    aliases: ['AL-HAYDAR'],
    type: 'person',
    dob: '1956-01-01',
    passportNumber: '01030941',
  },
  {
    id: 'UAE-P-085',
    name: 'YAHIA AL SAYED IBRAHIM MOHAMED MOUSA',
    aliases: ['MOUSA'],
    type: 'person',
    dob: '1984-05-05',
  },
  {
    id: 'UAE-P-086',
    name: 'MOHAMMED GAMAL AHMED HESHMAT ABDELHAMEED',
    aliases: ['ABDELHAMEED'],
    type: 'person',
  },
  {
    id: 'UAE-P-087',
    name: 'ALSAYED MAHMOUD EZZAT IBRAHIM EISSA',
    aliases: ['EISSA'],
    type: 'person',
  },
  {
    id: 'UAE-P-088',
    name: 'QADRI MOHAMMED FAHIM MAHMOUD AL-SHAIKH',
    aliases: ['AL-SHAIKH'],
    type: 'person',
    dob: '1972-11-02',
    passportNumber: '618452',
  },
  {
    id: 'UAE-P-089',
    name: 'ALAA ALI ALI MOHAMMED AL-SAMAHI',
    aliases: ['AL-SAMAHI'],
    type: 'person',
    dob: '1976-01-01',
  },
  {
    id: 'UAE-P-090',
    name: 'MAS\'UD NIKBAKHT',
    aliases: ['NIKBAKHT'],
    type: 'person',
    dob: '1943-01-01',
    passportNumber: '2042004010355827',
  },
  {
    id: 'UAE-P-091',
    name: 'SA\'ID NAJAFPUR',
    aliases: ['NAJAFPUR'],
    type: 'person',
  },
  {
    id: 'UAE-P-092',
    name: 'MOHAMMAD HASAN KHODA\'I',
    aliases: ['KHODA\'I'],
    type: 'person',
  },
  {
    id: 'UAE-P-093',
    name: 'MOHAMMADREZA KHEDMATI VALADZAGHARD',
    aliases: ['VALADZAGHARD'],
    type: 'person',
    dob: '1986-05-04',
    passportNumber: 'N35635875',
  },
  {
    id: 'UAE-P-094',
    name: 'MEGHDAD AMINI',
    aliases: ['AMINI'],
    type: 'person',
    dob: '1982-05-06',
    passportNumber: 'U36089349',
  },
  {
    id: 'UAE-P-095',
    name: 'FOAD SALEHI',
    aliases: ['SALEHI'],
    type: 'person',
    dob: '1986-04-28',
    passportNumber: '25265428',
  },
  {
    id: 'UAE-P-096',
    name: 'MOHAMMAD EBRAHIM OWHADI',
    aliases: ['OWHADI'],
    type: 'person',
  },
  {
    id: 'UAE-P-097',
    name: 'ESMA\'IL RAZAVI',
    aliases: ['RAZAVI'],
    type: 'person',
  },
  {
    id: 'UAE-P-098',
    name: 'ABDULLAH SAMAD FAROQUI',
    aliases: ['FAROQUI'],
    type: 'person',
  },
  {
    id: 'UAE-P-099',
    name: 'MOHAMMAD DAWOOD',
    aliases: ['Mzml'],
    type: 'person',
    dob: '1983-01-01',
  },
  {
    id: 'UAE-P-100',
    name: 'ABDUL RAHIM MANAN',
    aliases: ['MANAN'],
    type: 'person',
    dob: '1962-01-01',
  },
  {
    id: 'UAE-P-101',
    name: 'MOHAMMAD NAEEM BARICH',
    aliases: ['BARICH'],
    type: 'person',
    dob: '1975-01-01',
  },
  {
    id: 'UAE-P-102',
    name: 'SADR IBRAHIM',
    aliases: ['IBRAHIM'],
    type: 'person',
  },
  {
    id: 'UAE-P-103',
    name: 'ABDUL AZIZ SHAH ZAMANI',
    aliases: ['ZAMANI'],
    type: 'person',
    dob: '1985-01-01',
    nationality: 'Pakistan',
    passportNumber: 'AP1810244',
  },
  {
    id: 'UAE-P-104',
    name: 'HAFEEZ ABDUL MAJEED',
    aliases: ['ABDUL MAJEED'],
    type: 'person',
    dob: '1972-01-01',
    nationality: 'Pakistan',
  },
  {
    id: 'UAE-P-105',
    name: 'ABD-AL RAHMAN \'ALI HUSAYN AL-AHMAD AL-RAWI',
    aliases: ['AL-RAWI'],
    type: 'person',
  },
  {
    id: 'UAE-P-106',
    name: 'SAYED HABIB AHMAD KHAN',
    aliases: ['KHAN'],
    type: 'person',
    dob: '1970-01-01',
    passportNumber: 'P2502071',
  },
  {
    id: 'UAE-E-001',
    name: 'MUSLIM BROTHERHOOD IN THE UAE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-002',
    name: 'KHALAYA AL JIHAD AL-EMIRATI (UAE JAHADIST CELLS)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-003',
    name: 'OMMAH PARTY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-004',
    name: 'AL QAEDA (AQ)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-005',
    name: 'ISLAMIC STATE OF IRAQ AND THE LEVANT (ISIS)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-006',
    name: 'AL-QA\'IDA IN THE ARABIAN PENINSULA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-007',
    name: 'ANSAR AL-SHARIA(SUPPORTERS OF SHARIA LAW ) IN YEMEN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-008',
    name: 'THE MUSLIM BROTHERHOOD',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-009',
    name: 'ISLAMIC GROUB IN EGYPT',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-010',
    name: 'ANSAR BAIT AL-MAQDIS (WILAYAT SINAI- PROVINCE OR STATE IN THE SINAI)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-011',
    name: 'AJNAD MISR',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-012',
    name: 'THE HOUTHI MOVEMENT IN YEMEN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-013',
    name: 'HEZBOLLAH AL-HIJAZ IN SAUDI ARABIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-014',
    name: 'HEZBOLLAH IN THE GULF COOPERATION COUNCIL',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-015',
    name: 'AL-QAIDA ORGNAISATION IN IRAN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-016',
    name: 'BADER ORGANISATION IN IRAQ',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-017',
    name: 'ASAAIB AHL AL-HAQ (LEAGUE OF THE RIGHTEOUS) IN IRAQ',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-018',
    name: 'HEZBOLLAH BRIGADE IN IRAQ',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-019',
    name: 'LIWA ABU AL-FADL AL-ABBAS IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-020',
    name: 'AL-YOUM AL-MAOUD BRIGADE IN IRAQ',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-021',
    name: 'OMAR BIN YASSER BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-022',
    name: 'ANSAR AL-ISLAM',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-023',
    name: 'AL-NUSRAH FRONT IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-024',
    name: 'HARAKET AHRAR ASHAM IN SYRIA (ISLAMIC MOVEMENT OF THE FREE MAN OF THE LEVENT)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-025',
    name: 'THE ARMY OF ISLAM IN PALESTINE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-026',
    name: 'ABDALLAH AZZAM BRIGADES',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-027',
    name: 'FATAH AL ISLAM IN LEBANON',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-028',
    name: 'ASBAT AL-ANSAR IN LEBANON',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-029',
    name: 'AL QAIDA IN THE LAND OF THE ISLAMIC MAGHREB',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-030',
    name: 'ANSAR AL-SHARIA IN LIBYA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-031',
    name: 'ANSAR AL-SHARI\'A IN TUNISIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-032',
    name: 'MUJAHIDEEN YOUTH MOVEMENT IN SOMALIA(HARAKET AL-SHABAAB AL-MUJAHIDEEN IN SOMALIA)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-033',
    name: 'BOKO HARAM IN NIGERIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-034',
    name: 'ALMOURABITOUN GROUB IN MALI(THE SENTINELS)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-035',
    name: 'ANSAR AL-DINE IN MALI',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-036',
    name: 'THE HAQQANI NETWORK IN PAKISTAN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-037',
    name: 'LASHKAR E-TAYYIBA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-038',
    name: 'EAST TURKISTAN MOVEMENT IN PAKISTAN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-039',
    name: 'JAISH-I-MOHAMMED IN PAKISTAN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-040',
    name: 'JAISH-E-MOHAMMED (THE ARMY OF MOHAMMAD IN PAKISTAN AND INDIA)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-041',
    name: 'AL-MUJAHIDEEN AL-HONOUD IN KASHMIR/INDIA (THE INDIAN MUJAHIDEEN)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-042',
    name: 'CAUCASUS EMIRATE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-043',
    name: 'THE ISLAMIC MOVEMENT OF UZBEKISTAN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-044',
    name: 'ABU SAYYAF GROUP',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-045',
    name: 'TAHRIK-E TALIBAN PAKISTAN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-046',
    name: 'ABU-DHAR AL-GHIFARI BATTALION IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-047',
    name: 'AL-TAWHEED BRIGADE IN SYRIA(BRIGADE OF UNITY,OR MONOTHEISM)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-048',
    name: 'AL-TAWHID WAL-EMAN BATTALION IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-049',
    name: 'KATIBAT AL-KHADRA IN SYRIA(THE GREEN BATTALTION)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-050',
    name: 'ABU BAKR AL-SIDDIQ BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-051',
    name: 'TALHA BIN OBAIDULLAH BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-052',
    name: 'AL-SARIM AL-BATTAR BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-053',
    name: 'ABDULLAH IBN MUBARAK BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-054',
    name: 'CONVOYS OF MARTYRS BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-055',
    name: 'ABU-OMER BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-056',
    name: 'AHRAR SHAMMAR BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-057',
    name: 'SARIYAT AL-JABAL BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-058',
    name: 'AL-SHAHBA BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-059',
    name: 'ALQAQAA BRIGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-060',
    name: 'SUFIAN AL-THAWRI BRGADE IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-061',
    name: 'EBAD AL-RAHMAN BRIGADE IN SYRIA(BRIGADE OF SOLDIERS OF ALLAH)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-062',
    name: 'OMAR IBN AL-KHATTAB BATTALION IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-063',
    name: 'AL-SHAYMA BATTALTION IN SYRIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-064',
    name: 'KATIBAT AL-HAQ IN SYRIA (BRIGADE OF THE RIGHTEOUS)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-065',
    name: 'BENGHAZI DEFENSE BRIGADES',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-066',
    name: 'AL-ASHTAR BRIGADES',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-067',
    name: 'FEBRUARY 14 COALITION',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-068',
    name: 'THE POPULAR RESISTANCE BRIGADES IN BAHRAIN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-069',
    name: 'BAHRAINS HEZBOLLAH',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-070',
    name: 'SARAYA AL-MUKHTAR',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-071',
    name: 'BAHRAIN FREEDOM MOVEMENT',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-072',
    name: 'BENGHAZI REVOLUTIONARIES SHURA COUNCIL',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-073',
    name: 'AL-SARAYA MEDIA CENTER',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-074',
    name: 'RAFALLAH AL-SAHATI BRIGADE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-075',
    name: 'AL-KARAMA ORGANISATION',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-076',
    name: 'THE COUNCIL ON AMERICAN ISLAMIC RELATIONS (CAIR)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-077',
    name: 'CANVAS',
    aliases: ['CENTER FOR APPLIED NONVIOLENT ACTION AND STRATEGIES'],
    type: 'organization',
  },
  {
    id: 'UAE-E-078',
    name: 'MUSLIM AMERICAN SOCIETY (MAS)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-079',
    name: 'INTERNAIONAL UNION OF MUSLIM SCHOLARS (IUMS)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-080',
    name: 'FADERATION OF ISLAMIC ORGANISATION IN EUROPE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-081',
    name: 'UNION OF ISLAMIC ORGANISATION OF FRANCE (UOIF)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-082',
    name: 'MUSLIM ASSOCIATION OF BRITAIN (MAB)',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-083',
    name: 'ISLAMIC COMMUNITY OF GERMANY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-084',
    name: 'ISLAMIC ASSOCIATION OF DENMARK',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-085',
    name: 'ISLAMIC ASSOCIATION IN BELGIUM',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-086',
    name: 'ISAMIC ASSOCIATION OF ITALY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-087',
    name: 'ISLAMIC ASSOCIATION OF FINLAND',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-088',
    name: 'ISLAMIC ASSOCIATION OF SWEDEN',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-089',
    name: 'ISLAMIC ASSOCIATION OF NORWAY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-090',
    name: 'ISLAMIC AID',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-091',
    name: 'THE CORDOBA FOUNDATION',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-092',
    name: 'ISLAMIC RELETIEF WORLD WIDE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-093',
    name: 'QATAR VOLUNTEER CENTER',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-094',
    name: 'DOHA APPLE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-095',
    name: 'QATAR CHARITY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-096',
    name: 'EID CHARITY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-097',
    name: 'SHEIKH THANI BIN ABDULLAH FOUNDATION FOR HUMANITARIAN SERVICE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-098',
    name: 'AL-BALAGH CHARITABLE FOUNDATION',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-099',
    name: 'AL-IHSAN CHARITABLE SOCIETY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-100',
    name: 'ALRAHMA FOUNDATION FOR HUMAN DEVELOPMENT',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-101',
    name: 'BOSHRA NEWS AGENCY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-102',
    name: 'ALNABAA TV',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-103',
    name: 'TANASUH FOUNDATION FOR DAWA,CULTURE AND MEDIA',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-104',
    name: 'AL KHAYR SUPERMARKET',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-105',
    name: 'INTERNATIONAL ISLAMIC COUNCIL',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-106',
    name: 'INTERNATIONAL UNION OF MUSLIMS SCHOLARS',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-107',
    name: 'RASHED EXCHANGE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-108',
    name: 'JAHAN ARAS KISH',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-109',
    name: 'KHEDMATI AND COMPANY JOINT PARTNERSHIP',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-110',
    name: 'TAWASUL COMPANY',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-111',
    name: 'AL HARAM EXCHANGE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-112',
    name: 'AL KHALIDI EXCHANGE',
    aliases: [],
    type: 'organization',
  },
  {
    id: 'UAE-E-113',
    name: 'NEJAAT SOCIAL WALFARE ORGANIZATION (NEJAAT)',
    aliases: [],
    type: 'organization',
  },
];
